export interface DesignPreset {
  id: number;
  name: string;
  file: string;
  category: string;
  desc: string;
  theme: string;
}

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: 1,
    name: "Cyber Emerald",
    file: "design-1-cyber-emerald.html",
    category: "Neo-Brutalist",
    desc: "Raw Neo-Brutalist dark theme with thick black borders, emerald accents, and monospace type.",
    theme: "Dark / High Contrast",
  },
  {
    id: 2,
    name: "Mono Sand",
    file: "design-2-mono-sand.html",
    category: "Minimalist Serif",
    desc: "Light, refined minimalist paper look with warm charcoal, serif headings, and wide space margins.",
    theme: "Light / Serif",
  },
  {
    id: 3,
    name: "Synth Vapor",
    file: "design-3-synth-vapor.html",
    category: "Retrowave",
    desc: "Retro-futuristic retrowave theme with glowing cyber-cyan, neon pink grids, and scanlines.",
    theme: "Dark / Neon Glow",
  },
  {
    id: 4,
    name: "Helvetica Noir",
    file: "design-4-helvetica-noir.html",
    category: "Stark Editorial",
    desc: "Stark black-and-white asymmetric layout with bold line divisions and heavy typography.",
    theme: "Monochrome / Minimal",
  },
  {
    id: 5,
    name: "Tactical Rust",
    file: "design-5-tactical-rust.html",
    category: "Industrial Console",
    desc: "Industrial military console theme with warning hazard orange highlights, technical borders, and crosshairs.",
    theme: "Dark / Utilitarian",
  },
  {
    id: 6,
    name: "Obsidian Gold",
    file: "design-6-obsidian-gold.html",
    category: "Luxury Dark",
    desc: "Luxury premium dark style with champagne gold hairline accents, translucent cards, and soft Garamond type.",
    theme: "Dark / Premium",
  },
  {
    id: 7,
    name: "Pastel Blob",
    file: "design-7-pastel-blob.html",
    category: "Playful Claymorphic",
    desc: "Playful round claymorphic card layout with lilac/mint/peach pastel tones and bubble triggers.",
    theme: "Color / Rounded",
  },
  {
    id: 8,
    name: "Bauhaus Primary",
    file: "design-8-bauhaus-primary.html",
    category: "Swiss Grid",
    desc: "Modernist Bauhaus layout utilizing stark borders, primary color indicators, and strict grids.",
    theme: "Light / Swiss Modern",
  },
  {
    id: 9,
    name: "Glass Aurora",
    file: "design-9",
    category: "Glassmorphism",
    desc: "Elegant dark glassmorphism with glowing neon backdrops and sleek premium controls.",
    theme: "Dark / Translucent",
  },
  {
    id: 10,
    name: "Minimal Editorial",
    file: "design-10",
    category: "Modern Serif",
    desc: "Serif-driven high-fashion editorial grid with extreme whitespace and fine lines.",
    theme: "Light / Editorial",
  },
  {
    id: 11,
    name: "Clay Bento",
    file: "design-11",
    category: "Bento 3D",
    desc: "Warm claymorphic 3D cards in a Bento layout with smooth spring animations.",
    theme: "Color / Neumorphic",
  },
  {
    id: 12,
    name: "Midnight Glow",
    file: "design-12",
    category: "Cosmic Cyberpunk",
    desc: "Deep cosmic backdrop with cyan border glows, clean Outfit typography, and subtle tech elements.",
    theme: "Dark / High Glow",
  },
  {
    id: 13,
    name: "Soft Neumorphic",
    file: "design-13",
    category: "Light Neumorphic",
    desc: "Extremely soft tactile light-theme card UI with extruded buttons and responsive sliders.",
    theme: "Light / Tactile",
  },
  {
    id: 14,
    name: "Bold Brutalist",
    file: "design-14",
    category: "High Contrast",
    desc: "Aggressive, raw brutalism with solid fills, offset boxes, and thick borders.",
    theme: "Dark / Brutalist",
  },
  {
    id: 15,
    name: "Space Sleek",
    file: "design-15",
    category: "Sci-Fi HUD",
    desc: "Futuristic sci-fi dashboard theme with layout lines and minimalist neon status guides.",
    theme: "Dark / HUD",
  },
  {
    id: 16,
    name: "Retro Analog",
    file: "design-16",
    category: "Nostalgic Beige",
    desc: "Vibrant, nostalgia-inducing layout with warm beige paper, orange grid overlays, and pixel buttons.",
    theme: "Light / Analog",
  },
  {
    id: 17,
    name: "Signal Lock",
    file: "design-17",
    category: "Instrument UI",
    desc: "Void black + phosphor green meters. Precision-tool trust for technical creators.",
    theme: "Dark / Minimal",
  },
  {
    id: 18,
    name: "Tape Archive",
    file: "design-18",
    category: "Editorial Trust",
    desc: "Warm paper, serif headlines, reel metaphor. Calm conversion for interview podcasts.",
    theme: "Light / Heritage",
  },
  {
    id: 19,
    name: "Patchbay Pro",
    file: "design-19",
    category: "Studio Rack",
    desc: "Evolved Studio Console: gunmetal chassis, amber REC, live waveform in CRT. Recommended default.",
    theme: "Dark / Analog+",
  },
  {
    id: 20,
    name: "Timeline Master",
    file: "design-20",
    category: "Edit-First",
    desc: "Waveform hero + multi-track lanes. Sells aligned masters and post-production.",
    theme: "Dark / Cyan",
  },
];
